include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    only_throw_errors: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
