name: hris_mobile
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0

  supercharged: ^2.0.0
  kartal: ^2.0.0
  flutter_form_builder: ^6.0.0
  sizer: ^2.0.12
  dio: ^4.0.0
  freezed_annotation: ^0.14.1
  odoo_rpc: ^0.4.3
  json_annotation: ^4.0.1
  flutter_secure_storage: ^4.2.0
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.3
  sliding_sheet: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.2
  very_good_analysis: ^2.0.0

  freezed: ^0.14.1+3
  build_runner: ^2.0.1
  json_serializable: ^4.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/
flutter_intl:
  enabled: true
  arb-dir: lib/l10n/arb
  class_name: AppLocalizations